/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "pData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pz_NamePlate, pz_NamePlate, AUTO)


PB_BIND(pz_PowerMeasure, pz_PowerMeasure, AUTO)


PB_BIND(pz_JobCard, pz_JobCard, AUTO)









